### ISSUE TITLE
Installing build prerequisites fails (packages not found)

### ISSUE THREAD

**Issue by 3dRikal** [ChrisTitusTech/linutil#850] opened 2024-10-19 21:12 UTC
## Describe the bug
Install Build Prerequisites. Starts but fails to retrieve any packages

## To Reproduce
1. on CatchyOS, loadlinutil (curl used)
2. select System Setup
3. Select Build Prerequisites
4. See screenshot

## Expected behavior
Pulls all the relevant packages

## Additional context
catchyos on ryzen 5900x
See Neovim for details 

           .-------------------------:                    jsoucy@roukydesk-catchy
          .+=========================.                    -----------------------
         :++===++==================-       :++-           OS: CachyOS Linux x86_64
        :*++====+++++=============-        .==:           Kernel: Linux 6.11.4-2-cachyos
       -*+++=====+***++==========:                        Uptime: 9 hours, 3 mins
      =*++++========------------:                         Packages: 1529 (pacman)
     =*+++++=====-                     ...                Shell: fish 3.7.1
   .+*+++++=-===:                    .=+++=:              Display (AW3423DWF): 3440x1440 @ 165 Hz (as 2752x1152) in 34" [External] [HDR]
  :++++=====-==:                     -*****+              DE: KDE Plasma 6.2.1
 :++========-=.                      .=+**+.              WM: KWin (Wayland)
.+==========-.                          .                 WM Theme: Breeze
 :+++++++====-                                .--==-.     Theme: Breeze (Dark) [Qt], Breeze-Dark [GTK2], Breeze [GTK3]
  :++==========.                             :+++++++:    Icons: breeze-dark [Qt], breeze-dark [GTK2/3/4]
   .-===========.                            =*****+*+    Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
    .-===========:                           .+*****+:    Cursor: capitaine (24px)
      -=======++++:::::::::::::::::::::::::-:  .---:      Terminal: konsole 24.8.2
       :======++++====+++******************=.             CPU: AMD Ryzen 9 5900X (24) @ 3.70 GHz
        :=====+++==========++++++++++++++*-               GPU: AMD Radeon RX 7900 XTX [Discrete]
         .====++==============++++++++++*-                Memory: 7.78 GiB / 31.25 GiB (25%)
          .===+==================+++++++:                 Swap: 0 B / 31.25 GiB (0%)
           .-=======================+++:                  Disk (/): 30.17 GiB / 1.82 TiB (2%) - btrfs
             ..........................                   Disk (/mnt/games): 498.32 GiB / 1.82 TiB (27%) - btrfs
                                                          Disk (/mnt/ssd): 607.54 GiB / 1.82 TiB (33%) - fuseblk
                                                          Local IP (enp5s0): 10.0.0.103/16
                                                          Locale: en_CA.UTF-8

                                                                                  
                                                                                  

## Checklist
- [X] I checked for duplicate issues.
- [X] I checked already existing discussions.
- [?] This issue is not included in the roadmap.
- [ONLY TESTED STABLE] This issue is present on both stable and development branches.
![Screenshot_20241019_170511](https://github.com/user-attachments/assets/93a5e250-2a1c-4461-924b-f4c1b3c53862)

**Comment by cartercanedy** [comment] 2024-10-19 22:44
Looks like a dupe of #817. Please try to build from source

**Closed** 2024-10-23 14:00 UTC
Labels: bug
