### ISSUE TITLE
Arch-server-installation problem

### ISSUE THREAD

**Issue by b0b0smrad** [ChrisTitusTech/linutil#301] opened 2024-09-07 13:30 UTC
The installation stop after grub install and check:
chroot: failed to run command '/bin/bash': No such file or directory.
After that installation Fails, it exist from arch only half installing it:
To reproduce the problem run arch in qemu on arch64.

**Comment by nnyyxxxx** [comment] 2024-09-20 08:05
Should be resolved with the new release, could not reproduce.

/close

**Closed** 2024-09-20 08:06 UTC
