### ISSUE TITLE
 System Setup > Build Prerequisites > asking for Username and passwd for github

### ISSUE THREAD

**Issue by AyakoGFX** [ChrisTitusTech/linutil#95] opened 2024-07-30 19:50 UTC
## To Reproduce
1. Go to ''System Setup"
2. Click on "Build Prerequisites"
3. See error "asking fot Username and passwd for github"
![errorpng](https://github.com/user-attachments/assets/0984e45d-77f4-44bd-a7e1-ecccf44be12f)

**Comment by lj3954** [comment] 2024-07-30 22:22
Fixed in #54. Duplicate of #50.

**Comment by Compourri** [comment] 2024-08-01 11:18
> Fixed in #54. Duplicate of #50.

Problem still there. Not fixed.

**Comment by lj3954** [comment] 2024-08-01 20:21
Yes, it is. Don't use the stable release, there have been countless fixes since.

**Comment by AyakoGFX** [comment] 2024-08-02 16:02
it is fixed now

**Closed** 2024-08-02 16:10 UTC
