### ISSUE TITLE
broken KDE 6.1.4

### ISSUE THREAD

**Issue by jcv99** [ChrisTitusTech/linutil#288] opened 2024-09-06 15:54 UTC
## Describe the bug
All the default kde theme changed after installing global theme. And I want to know how to roll it back. Also it broke the settings and dark mode, as seen in the photo.
Broken settings:
keyboard shortcuts ,sound, display and monitor, bluetooth, thunderbolt,colour management
printers, wifi, wallpaper, global themes, text and fonts and more...
1. Execute the script
2. Execute global settings
3. Reboot

## Expected behavior
Settings functioning well and dark mode enabled. Also a way to revert it
## Screenshots
![image](https://github.com/user-attachments/assets/500e117b-5ba6-4dde-b209-4041c9780044)

## Additional context
I get it if it's not possible to revert it, but at least I want to show the errors I have it. Also I guess if I try to remove things maybe will it work(I don't want to restart the distro another time)

**Comment by GreatNovaDragon** [comment] 2024-09-07 09:14
It attempts to set Breeze as a kvantum theme, when on arch and fedora at least, there is no kvantum theme named "Breeze" installed.

**Comment by Kingproone** [comment] 2024-09-07 09:58
I deleted the packages that the `global theme` option installed, after a reboot it reverted back to my set theme.

**Comment by GreatNovaDragon** [comment] 2024-09-07 12:14
Apparently an Breeze Kvantum theme straight up doesnt exist anywhere, and thats the core of this issue. 

The Global Theme script attempts to put use the qt6-theme controll application as the global QT-Theme (which you do outside of KDE), and in the qt6 controll application, then sets kvantum (an theme-engine) as its theme. Still correct.

Then for kvantum, a non-existent kvantum theme is set, which is the issue. I cant exactly guess if its light mode or dark mode, but i presume its light mode, so rather than setting it to Breeze, the default KDE Theme that has no kvantum equivalent, it should be set to something else. 

Now, here is where Chris' Preferences for themeing set in. I personally would replace that line setting the kvantum theme from breeze to KvArc, but thats my preference.

**Comment by adamperkowski** [comment] 2024-09-20 21:20
This is a duplicate of #165.
/close

**Closed** 2024-09-20 21:20 UTC
